### ISSUE TITLE
Doesn't work on rails < 4.2

### ISSUE THREAD

**Issue by adis-io** [64kramsystem/json_on_rails#15]
Shows this error: `NameError: uninitialized constant ActiveRecord::Type::Value`

**Comment by saveriomiroddi** [comment]
Hello! I'll have a look at it, but I can't promise anything, since Rails versions < 4.2 [are not supported anymore](https://guides.rubyonrails.org/maintenance_policy.html) :grimacing:.

**Comment by saveriomiroddi** [comment]
Error and relevant stack trace:

```<gems_root>/activesupport-4.1.0/lib/active_support/values/time_zone.rb:285: warning: circular argument reference - now
<gems_root>/json_on_rails-0.2.0/lib/active_record/type/json.rb:11:in `<module:Type>': uninitialized constant ActiveRecord::Type::Value (NameError)
  from <gems_root>/json_on_rails-0.2.0/lib/active_record/type/json.rb:10:in `<module:ActiveRecord>'
  from <gems_root>/json_on_rails-0.2.0/lib/active_record/type/json.rb:9:in `<top (required)>'
  from <gems_root>/json_on_rails-0.2.0/lib/active_record/connection_adapters/mysql2_json_adapter.rb:4:in `require'
  from <gems_root>/json_on_rails-0.2.0/lib/active_record/connection_adapters/mysql2_json_adapter.rb:4:in `<top (required)>'
  from <gems_root>/json_on_rails-0.2.0/lib/json_on_rails.rb:4:in `require_relative'
  from <gems_root>/json_on_rails-0.2.0/lib/json_on_rails.rb:4:in `<top (required)>'
  [...]
```

**Comment by saveriomiroddi** [comment]
I spent some time, and I'm not sure, considering the fact that Rails 4.1 is unsupported, whether I'll implement the support in the gem or less.

A good starting point is to trace `lib/active_record/attribute_methods/read.rb#read_attribute()` in ActiveRecord (4.1), and see where the cast is performed - the structure is considerably different from ActiveRecord 4.2.

Unfortunately, I also hit a possible bug in the mysql2 gem, which added up. It's a segfault, so it should never happen:

```
2.4.6 :001 > MyModel.all
  MyModel Load (0.2ms)  SELECT `my_models`.* FROM `my_models`
<gems_path>/activerecord-4.2.11.1/lib/active_record/connection_adapters/mysql2_adapter.rb:57: [BUG] Segmentation fault at 0x0000000000000ba9
ruby 2.4.6p354 (2019-04-01 revision 67394) [x86_64-linux]
```

**Comment by saveriomiroddi** [comment]
The bug mentioned, that blocked me this morning, is actually a `mysql2` issue: https://github.com/brianmario/mysql2/issues/1063.

**Comment by 64kramsystem** [comment]
> Shows this error: `NameError: uninitialized constant ActiveRecord::Type::Value`

Hello! Given the (non-existent) popularity of this gem, the fact that Rails 4.1 is discontinued, and that I have other priority tasks (and not enough time), I've updated the documentation and code to make clear that the gem works only on 4.1.

The architecture of ActiveRecord 4.1 is different in an unfortunately non-trivial way, so it takes more than a short time to add the support.

I'm leaving this issue open though, and adding the `good first issue` label, in case anybody wants to pick it up :-)

Thanks for reporting, though!
